name: Trigger auto deployment for mcp-cwm

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mcp-cwm-AutoDeployTrigger-5d73f196-c1cd-4ce3-9d29-5d6c02e2ddf9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MCPCWM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MCPCWM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MCPCWM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: mcpevu8bwg2.azurecr.io
          registryUsername: ${{ secrets.MCPCWM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MCPCWM_REGISTRY_PASSWORD }}
          containerAppName: mcp-cwm
          resourceGroup: gcspa
          imageToBuild: mcpevu8bwg2.azurecr.io/mcp-cwm:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


